### ISSUE TITLE
Uncaught (in promise) Error: No output type specified.

### ISSUE THREAD

**Issue by aafenlared** [hongfaqiu/shp-write-multi#3]
Hi, I was trying out your library. But I have the error Uncaught (in promise) Error: No output type specified. in console. What am I missing here?

**Comment by hongfaqiu** [comment]
Could you provide your code to debug

**Comment by matheus2m** [comment]
Same error here, i was thinking maybe is my geojson but i tested with the example code and threw the same error. 

`Error: No output type specified.
    at n.generateInternalStream (https://j7d2iv.csb.app/node_modules/jszip/dist/jszip.min.js:13:17045)

    at n.generateAsync (https://j7d2iv.csb.app/node_modules/jszip/dist/jszip.min.js:13:17444)

    at module.exports (https://j7d2iv.csb.app/node_modules/shp-write-multi/src/zip.js:46:28)

    at module.exports [as download] (https://j7d2iv.csb.app/node_modules/shp-write-multi/src/download.js:4:25)

    at _callee$ (https://j7d2iv.csb.app/src/index.js:32:29)

    at tryCatch (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)

    at Generator.eval (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)

    at Generator.eval [as next] (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)

    at asyncGeneratorStep (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)

    at _next (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)

    at eval (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7)

    at new Promise (<anonymous>)

    at HTMLButtonElement.eval (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)

    at HTMLButtonElement._download (https://j7d2iv.csb.app/src/index.js:68:20)

    at [HTMLButtonElement.download](http://htmlbuttonelement.download/) (https://j7d2iv.csb.app/src/index.js:10:20)`

code example: https://codesandbox.io/s/upbeat-scooby-j7d2iv?file=/src/index.js

**Comment by hongfaqiu** [comment]
> Same error here, i was thinking maybe is my geojson but i tested with the example code and threw the same error.
> 
> `Error: No output type specified. at n.generateInternalStream (https://j7d2iv.csb.app/node_modules/jszip/dist/jszip.min.js:13:17045)
> 
> ```
> at n.generateAsync (https://j7d2iv.csb.app/node_modules/jszip/dist/jszip.min.js:13:17444)
> 
> at module.exports (https://j7d2iv.csb.app/node_modules/shp-write-multi/src/zip.js:46:28)
> 
> at module.exports [as download] (https://j7d2iv.csb.app/node_modules/shp-write-multi/src/download.js:4:25)
> 
> at _callee$ (https://j7d2iv.csb.app/src/index.js:32:29)
> 
> at tryCatch (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
> 
> at Generator.eval (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
> 
> at Generator.eval [as next] (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
> 
> at asyncGeneratorStep (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
> 
> at _next (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
> 
> at eval (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7)
> 
> at new Promise (<anonymous>)
> 
> at HTMLButtonElement.eval (https://j7d2iv.csb.app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)
> 
> at HTMLButtonElement._download (https://j7d2iv.csb.app/src/index.js:68:20)
> 
> at [HTMLButtonElement.download](http://htmlbuttonelement.download/) (https://j7d2iv.csb.app/src/index.js:10:20)`
> ```
> 
> code example: https://codesandbox.io/s/upbeat-scooby-j7d2iv?file=/src/index.js

Sorry for my late reply because of the Spring Festival, I have fix this error in browser caused by the jszip's broken update in v3.

**Comment by hongfaqiu** [comment]
Now you can install the new version v1.1.2, which fixed this error
